version: "3.9"
services:
  api:
    build: .
    container_name: tdlib
    restart: always
    ports:
      - "8189:8080"
    depends_on:
      - redis-server
    environment:
      PORT: 8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf